version: '3.6'

services:
  backend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - './:/app/server'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - PORT=3000
    container_name: boilerplate-backend
    restart: always
